import type { Metadata } from "next";
import {Roboto, Montserrat} from "next/font/google"
// import localFont from "next/font/local";
import "./globals.css";

const roboto = Roboto({
  subsets: ['latin'],
  weight: "900",
  display: "swap",
  variable: '--font-roboto'
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "700",
  display: "swap",
  variable: "--font-montserrat"
})
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${montserrat.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
